name: social_embed_webview
description: Provide a widget to easily embed social media post in flutter using web embed feature by the platform.
version: 0.3.2
homepage: https://github.com/aker99/social_embed_webview

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0
  url_launcher: ^6.3.1
  localstorage: ^5.0.0
  http: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

