name: social_embed_webview
description: Provide a widget to easily embed social media post in flutter using web embed feature by the platform.
version: 0.3.2
homepage: https://github.com/aker99/social_embed_webview

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^2.0.4
  url_launcher: ^6.0.3
  localstorage: ^4.0.0+1
  http: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

